# head = 2, chest = 3, boots = 5, gloves = 6

armors = {
    # ----- Light -----
    # 1 - Rags
    'tattered_headwrap': {
        'name': 'Tattered Headwrap',
        'description': 'TODO',
        'level': 1,
        'weight': 1,
        '_itype': 2,
        'bonus_init': 1
    },
    'tattered_cloak': {
        'name': 'Tattered Cloak',
        'description': 'TODO',
        'level': 1,
        'weight': 2,
        '_itype': 3,
        'bonus_init': 1,
        'bonus_carry': 10
    },
    'tattered_footwraps': {
        'name': 'Tattered Footwraps',
        'description': 'TODO',
        'level': 1,
        'weight': 1,
        '_itype': 5,
        'bonus_init': 1
    },
    'tattered_handwraps': {
        'name': 'Tattered Handwraps',
        'description': 'TODO',
        'level': 1,
        'weight': 1,
        '_itype': 6,
        'bonus_init': 1
    },
    # 3 - Cloth
    'cloth_hat': {
        'name': 'Cloth Hat',
        'description': 'TODO',
        'level': 3,
        'weight': 2,
        '_itype': 2,
        'bonus_init': 1,
        'bonus_electric_res': 0.01,
    },
    'cloth_armor': {
        'name': 'Cloth Armor',
        'description': 'TODO',
        'level': 3,
        'weight': 3,
        '_itype': 3,
        'bonus_init': 1,
        'bonus_carry': 10,
        'bonus_electric_res': 0.01,
    },
    'cloth_boots': {
        'name': 'Cloth Boots',
        'description': 'TODO',
        'level': 3,
        'weight': 2,
        '_itype': 5,
        'bonus_init': 1,
        'bonus_electric_res': 0.01,
    },
    'cloth_gloves': {
        'name': 'Cloth Gloves',
        'description': 'TODO',
        'level': 3,
        'weight': 2,
        '_itype': 6,
        'bonus_init': 1,
        'bonus_electric_res': 0.01,
    },
    # 5 - Boiled Leather
    'boiled_leather_helm': {
        'name': 'Boiled Leather Helm',
        'description': 'TODO',
        'level': 5,
        'weight': 4,
        '_itype': 2,
        'bonus_earth_res': 0.01,
        'bonus_fire_res': 0.01,
        'bonus_electric_res': 0.01,
        'bonus_water_res': 0.01,
    },
    'boiled_leather_armor': {
        'name': 'Boiled Leather Armor',
        'description': 'TODO',
        'level': 5,
        'weight': 8,
        '_itype': 3,
        'bonus_carry': 20,
        'bonus_earth_res': 0.01,
        'bonus_fire_res': 0.01,
        'bonus_electric_res': 0.01,
        'bonus_water_res': 0.01,
    },
    'boiled_leather_boots': {
        'name': 'Boiled Leather Boots',
        'description': 'TODO',
        'level': 5,
        'weight': 4,
        '_itype': 5,
        'bonus_init': 1,
        'bonus_earth_res': 0.01,
        'bonus_fire_res': 0.01,
        'bonus_electric_res': 0.01,
        'bonus_water_res': 0.01,
    },
    'boiled_leather_gloves': {
        'name': 'Boiled Leather Gloves',
        'description': 'TODO',
        'level': 5,
        'weight': 4,
        '_itype': 6,
        'bonus_init': 1,
        'bonus_earth_res': 0.01,
        'bonus_fire_res': 0.01,
        'bonus_electric_res': 0.01,
        'bonus_water_res': 0.01,
    },
    # 7 - Studded Leather
    # 9 - Chainmail
    # ----- Heavy ------
    # 1 - Rusty
    'rusty_helmet': {
        'name': 'Rusty Helmet',
        'description': 'TODO',
        'level': 1,
        'weight': 3,
        '_itype': 2,
        'bonus_init': -1,
        'bonus_earth_res': 0.01,
    },
    'rusty_armor': {
        'name': 'Rusty Armor',
        'description': 'TODO',
        'level': 1,
        'weight': 8,
        '_itype': 3,
        'bonus_init': -1,
        'bonus_carry': 10,
        'bonus_earth_res': 0.01,
    },
    'rusty_boots': {
        'name': 'Rusty Boots',
        'description': 'TODO',
        'level': 1,
        'weight': 3,
        '_itype': 5,
        'bonus_earth_res': 0.01,
    },
    'rusty_gauntlets': {
        'name': 'Rusty Gauntlets',
        'description': 'TODO',
        'level': 1,
        'weight': 3,
        '_itype': 6,
        'bonus_earth_res': 0.01,
    },
    # 3 - Wood
    'wood_helmet': {
        'name': 'Wooden Helmet',
        'description': 'TODO',
        'level': 3,
        'weight': 3,
        '_itype': 2,
        'bonus_init': -1,
        'bonus_earth_res': 0.01,
        'bonus_electricity_res': 0.01,
        'bonus_water_res': 0.01,
    },
    'wood_armor': {
        'name': 'Wooden Armor',
        'description': 'TODO',
        'level': 3,
        'weight': 7,
        '_itype': 3,
        'bonus_init': -1,
        'bonus_carry': 10,
        'bonus_earth_res': 0.01,
        'bonus_electricity_res': 0.01,
        'bonus_water_res': 0.01,
    },
    'wood_guards': {
        'name': 'Wooden Guards',
        'description': 'TODO',
        'level': 3,
        'weight': 3,
        '_itype': 5,
        'bonus_earth_res': 0.01,
        'bonus_electricity_res': 0.01,
        'bonus_water_res': 0.01,
    },
    'wood_gloves': {
        'name': 'Wooden Padded Gloves',
        'description': 'TODO',
        'level': 3,
        'weight': 2,
        '_itype': 6,
        'bonus_earth_res': 0.01,
        'bonus_electricity_res': 0.01,
        'bonus_water_res': 0.01,
    },
    # 5 - Bronze
    'bronze_helmet': {
        'name': 'Bronze Helmet',
        'description': 'TODO',
        'level': 5,
        'weight': 8,
        '_itype': 2,
        'bonus_init': -1,
        'bonus_earth_res': 0.02,
        'bonus_fire_res': 0.02,
        'bonus_water_res': 0.01,
    },
    'bronze_armor': {
        'name': 'Bronze Armor',
        'description': 'TODO',
        'level': 5,
        'weight': 15,
        '_itype': 3,
        'bonus_init': -2,
        'bonus_carry': 10,
        'bonus_earth_res': 0.02,
        'bonus_fire_res': 0.02,
        'bonus_water_res': 0.01,
    },
    'bronze_sabotons': {
        'name': 'Bronze Sabotons',
        'description': 'TODO',
        'level': 5,
        'weight': 7,
        '_itype': 5,
        'bonus_earth_res': 0.02,
        'bonus_fire_res': 0.02,
        'bonus_water_res': 0.01,
    },
    'bronze_gloves': {
        'name': 'Bronze Padded Gloves',
        'description': 'TODO',
        'level': 5,
        'weight': 5,
        '_itype': 6,
        'bonus_earth_res': 0.02,
        'bonus_fire_res': 0.02,
        'bonus_water_res': 0.01,
    },
    # 7 - Iron
    # 9 - Steel
    # ----- Ceremonial -----
    # 3
    'worn_headband': {
        'name': 'Worn Headband',
        'description': 'TODO',
        'level': 3,
        'weight': 3,
        '_itype': 2,
        'bonus_stamina_regen': 1,
    },
    'worn_coat': {
        'name': 'Worn Coat',
        'description': 'TODO',
        'level': 3,
        'weight': 3,
        '_itype': 3,
        'bonus_carry': 10,
        'bonus_electricity_res': 0.01,
        'bonus_water_res': 0.01,
        'bonus_stamina': 10,
    },
    'worn_hakama': {
        'name': 'Worn Hakama',
        'description': 'TODO',
        'level': 3,
        'weight': 3,
        '_itype': 5,
        'bonus_electricity_res': 0.01,
        'bonus_water_res': 0.01,
        'bonus_stamina': 10,
    },
    # ----- Spiritual -----
    # 3
    'vine_circlet': {
        'name': 'Vine Circlet',
        'description': 'TODO',
        'level': 3,
        'weight': 3,
        '_itype': 2,
        'bonus_mana_regen': 1,
    },
    'fur_robe': {
        'name': 'Fur Robe',
        'description': 'TODO',
        'level': 3,
        'weight': 4,
        '_itype': 3,
        'bonus_carry': 10,
        'bonus_electricity_res': 0.01,
        'bonus_water_res': 0.01,
        'bonus_mana': 20,
    },
}
