# head = 2, chest = 3, boots = 5, gloves = 6

armors = {
    # ----- Light -----
    # 1 - Rags
    'tattered_headwrap': {'name': 'Tattered Headwrap', 'description': 'TODO', 'level': 1, 'weight': 1, '_itype': 2,
                          'bonus_strength': 0, 'bonus_intelligence': 0, 'bonus_dexterity': 0, 'bonus_willpower': 0,
                          'bonus_health': 0, 'bonus_stamina': 0, 'bonus_mana': 0, 'bonus_init': 1, 'bonus_carry': 0,
                          'bonus_earth_res': 0.0, 'bonus_fire_res': 0.0, 'bonus_electricity_res': 0.0,
                          'bonus_water_res': 0.0,
                          'required_strength': 0,
                          'required_intelligence': 0, 'required_dexterity': 0, 'required_willpower': 0},
    'tattered_cloak': {'name': 'Tattered Cloak', 'description': 'TODO', 'level': 1, 'weight': 2, '_itype': 3,
                       'bonus_strength': 0, 'bonus_intelligence': 0, 'bonus_dexterity': 0, 'bonus_willpower': 0,
                       'bonus_health': 0, 'bonus_stamina': 0, 'bonus_mana': 0, 'bonus_init': 1, 'bonus_carry': 10,
                       'bonus_earth_res': 0.0, 'bonus_fire_res': 0.0, 'bonus_electricity_res': 0.0,
                       'bonus_water_res': 0.0,
                       'required_strength': 0,
                       'required_intelligence': 0, 'required_dexterity': 0, 'required_willpower': 0},
    'tattered_footwraps': {'name': 'Tattered Footwraps', 'description': 'TODO', 'level': 1, 'weight': 1, '_itype': 5,
                           'bonus_strength': 0, 'bonus_intelligence': 0, 'bonus_dexterity': 0, 'bonus_willpower': 0,
                           'bonus_health': 0, 'bonus_stamina': 0, 'bonus_mana': 0, 'bonus_init': 1, 'bonus_carry': 0,
                           'bonus_earth_res': 0.0, 'bonus_fire_res': 0.0, 'bonus_electricity_res': 0.0,
                           'bonus_water_res': 0.0,
                           'required_strength': 0,
                           'required_intelligence': 0, 'required_dexterity': 0, 'required_willpower': 0},
    'tattered_handwraps': {'name': 'Tattered Handwraps', 'description': 'TODO', 'level': 1, 'weight': 1, '_itype': 6,
                           'bonus_strength': 0, 'bonus_intelligence': 0, 'bonus_dexterity': 0, 'bonus_willpower': 0,
                           'bonus_health': 0, 'bonus_stamina': 0, 'bonus_mana': 0, 'bonus_init': 1, 'bonus_carry': 0,
                           'bonus_earth_res': 0.0, 'bonus_fire_res': 0.0, 'bonus_electricity_res': 0.0,
                           'bonus_water_res': 0.0,
                           'required_strength': 0,
                           'required_intelligence': 0, 'required_dexterity': 0, 'required_willpower': 0},
    # 3 - Cloth
    'cloth_hat': {'name': 'Cloth Hat', 'description': 'TODO', 'level': 3, 'weight': 2, '_itype': 2,
                  'bonus_strength': 0, 'bonus_intelligence': 0, 'bonus_dexterity': 0, 'bonus_willpower': 0,
                  'bonus_health': 0, 'bonus_stamina': 0, 'bonus_mana': 0, 'bonus_init': 1, 'bonus_carry': 0,
                  'bonus_earth_res': 0.0, 'bonus_fire_res': 0.0, 'bonus_electricity_res': 0.0,
                  'bonus_water_res': 0.0,
                  'required_strength': 0,
                  'required_intelligence': 0, 'required_dexterity': 0, 'required_willpower': 0},
    'cloth_armor': {'name': 'Cloth Armor', 'description': 'TODO', 'level': 3, 'weight': 3, '_itype': 3,
                    'bonus_strength': 0, 'bonus_intelligence': 0, 'bonus_dexterity': 0, 'bonus_willpower': 0,
                    'bonus_health': 0, 'bonus_stamina': 0, 'bonus_mana': 0, 'bonus_init': 1, 'bonus_carry': 10,
                    'bonus_earth_res': 0.0, 'bonus_fire_res': 0.0, 'bonus_electricity_res': 0.0,
                    'bonus_water_res': 0.0,
                    'required_strength': 0,
                    'required_intelligence': 0, 'required_dexterity': 0, 'required_willpower': 0},
    'cloth_boots': {'name': 'Cloth Boots', 'description': 'TODO', 'level': 3, 'weight': 2, '_itype': 5,
                    'bonus_strength': 0, 'bonus_intelligence': 0, 'bonus_dexterity': 0, 'bonus_willpower': 0,
                    'bonus_health': 0, 'bonus_stamina': 0, 'bonus_mana': 0, 'bonus_init': 1, 'bonus_carry': 0,
                    'bonus_earth_res': 0.0, 'bonus_fire_res': 0.0, 'bonus_electricity_res': 0.0,
                    'bonus_water_res': 0.0,
                    'required_strength': 0,
                    'required_intelligence': 0, 'required_dexterity': 0, 'required_willpower': 0},
    'cloth_gloves': {'name': 'Cloth Gloves', 'description': 'TODO', 'level': 3, 'weight': 2, '_itype': 6,
                     'bonus_strength': 0, 'bonus_intelligence': 0, 'bonus_dexterity': 0, 'bonus_willpower': 0,
                     'bonus_health': 0, 'bonus_stamina': 0, 'bonus_mana': 0, 'bonus_init': 1, 'bonus_carry': 0,
                     'bonus_earth_res': 0.0, 'bonus_fire_res': 0.0, 'bonus_electricity_res': 0.0,
                     'bonus_water_res': 0.0,
                     'required_strength': 0,
                     'required_intelligence': 0, 'required_dexterity': 0, 'required_willpower': 0},
    # 5 - Boiled Leather
    # 7 - Studded Leather
    # 9 - Chainmail
    # ----- Heavy ------
    # 1 - Rusty
    'rusty_helmet': {'name': 'Rusty Helmet', 'description': 'TODO', 'level': 1, 'weight': 3, '_itype': 2,
                     'bonus_strength': 0, 'bonus_intelligence': 0, 'bonus_dexterity': 0, 'bonus_willpower': 0,
                     'bonus_health': 0, 'bonus_stamina': 0, 'bonus_mana': 0, 'bonus_init': -1, 'bonus_carry': 0,
                     'bonus_earth_res': 0.01, 'bonus_fire_res': 0.0, 'bonus_electricity_res': 0.0,
                     'bonus_water_res': 0.0,
                     'required_strength': 3,
                     'required_intelligence': 0, 'required_dexterity': 0, 'required_willpower': 0},
    'rusty_armor': {'name': 'Rusty Armor', 'description': 'TODO', 'level': 1, 'weight': 8, '_itype': 3,
                    'bonus_strength': 0, 'bonus_intelligence': 0, 'bonus_dexterity': 0, 'bonus_willpower': 0,
                    'bonus_health': 0, 'bonus_stamina': 0, 'bonus_mana': 0, 'bonus_init': -1, 'bonus_carry': 10,
                    'bonus_earth_res': 0.01, 'bonus_fire_res': 0.0, 'bonus_electricity_res': 0.0,
                    'bonus_water_res': 0.0,
                    'required_strength': 3,
                    'required_intelligence': 0, 'required_dexterity': 0, 'required_willpower': 0},
    'rusty_boots': {'name': 'Rusty Boots', 'description': 'TODO', 'level': 1, 'weight': 3, '_itype': 5,
                    'bonus_strength': 0, 'bonus_intelligence': 0, 'bonus_dexterity': 0, 'bonus_willpower': 0,
                    'bonus_health': 0, 'bonus_stamina': 0, 'bonus_mana': 0, 'bonus_init': 0, 'bonus_carry': 0,
                    'bonus_earth_res': 0.01, 'bonus_fire_res': 0.0, 'bonus_electricity_res': 0.0,
                    'bonus_water_res': 0.0,
                    'required_strength': 3,
                    'required_intelligence': 0, 'required_dexterity': 0, 'required_willpower': 0},
    'rusty_gauntlets': {'name': 'Rusty Gauntlets', 'description': 'TODO', 'level': 1, 'weight': 3, '_itype': 6,
                        'bonus_strength': 0, 'bonus_intelligence': 0, 'bonus_dexterity': 0, 'bonus_willpower': 0,
                        'bonus_health': 0, 'bonus_stamina': 0, 'bonus_mana': 0, 'bonus_init': 0, 'bonus_carry': 0,
                        'bonus_earth_res': 0.01, 'bonus_fire_res': 0.0, 'bonus_electricity_res': 0.0,
                        'bonus_water_res': 0.0,
                        'required_strength': 3,
                        'required_intelligence': 0, 'required_dexterity': 0, 'required_willpower': 0},
    # 3 - Wood
    'wood_helmet': {'name': 'Wooden Helmet', 'description': 'TODO', 'level': 3, 'weight': 3, '_itype': 2,
                    'bonus_strength': 0, 'bonus_intelligence': 0, 'bonus_dexterity': 0, 'bonus_willpower': 0,
                    'bonus_health': 0, 'bonus_stamina': 0, 'bonus_mana': 0, 'bonus_init': -1, 'bonus_carry': 0,
                    'bonus_earth_res': 0.01, 'bonus_fire_res': 0.0, 'bonus_electricity_res': 0.01,
                    'bonus_water_res': 0.01,
                    'required_strength': 3,
                    'required_intelligence': 0, 'required_dexterity': 0, 'required_willpower': 0},
    'wood_armor': {'name': 'Wooden Armor', 'description': 'TODO', 'level': 3, 'weight': 7, '_itype': 3,
                   'bonus_strength': 0, 'bonus_intelligence': 0, 'bonus_dexterity': 0, 'bonus_willpower': 0,
                   'bonus_health': 0, 'bonus_stamina': 0, 'bonus_mana': 0, 'bonus_init': -1, 'bonus_carry': 10,
                   'bonus_earth_res': 0.01, 'bonus_fire_res': 0.0, 'bonus_electricity_res': 0.01,
                   'bonus_water_res': 0.01,
                   'required_strength': 3,
                   'required_intelligence': 0, 'required_dexterity': 0, 'required_willpower': 0},
    'wood_guards': {'name': 'Wooden Guards', 'description': 'TODO', 'level': 3, 'weight': 3, '_itype': 5,
                    'bonus_strength': 0, 'bonus_intelligence': 0, 'bonus_dexterity': 0, 'bonus_willpower': 0,
                    'bonus_health': 0, 'bonus_stamina': 0, 'bonus_mana': 0, 'bonus_init': 0, 'bonus_carry': 0,
                    'bonus_earth_res': 0.01, 'bonus_fire_res': 0.0, 'bonus_electricity_res': 0.01,
                    'bonus_water_res': 0.01,
                    'required_strength': 3,
                    'required_intelligence': 0, 'required_dexterity': 0, 'required_willpower': 0},
    'wood_gloves': {'name': 'Wooden Padded Gloves', 'description': 'TODO', 'level': 3, 'weight': 2, '_itype': 6,
                    'bonus_strength': 0, 'bonus_intelligence': 0, 'bonus_dexterity': 0, 'bonus_willpower': 0,
                    'bonus_health': 0, 'bonus_stamina': 0, 'bonus_mana': 0, 'bonus_init': 0, 'bonus_carry': 0,
                    'bonus_earth_res': 0.01, 'bonus_fire_res': 0.0, 'bonus_electricity_res': 0.01,
                    'bonus_water_res': 0.01,
                    'required_strength': 3,
                    'required_intelligence': 0, 'required_dexterity': 0, 'required_willpower': 0},
    # 5 - Bronze
    # 7 - Iron
    # 9 - Steel
}
