from elements import Elements
from weapon import WeaponType

weapons = {
    # Hammer/Str
    'rusty_hammer': {'name': 'Rusty Hammer', 'description': 'TODO', 'level': 1, 'weight': 3,
                     '_weapon_type': WeaponType.hammer.value, 'bonus_strength': 2, 'bonus_intelligence': 0,
                     'bonus_dexterity': 0, 'bonus_willpower': 0, 'bonus_health': 0, 'bonus_stamina': 0, 'bonus_mana': 0,
                     'bonus_init': 0, 'base_crit_chance': 0.05, 'damages': [[1, 4, Elements.earth.value]],
                     'crit_damage': 0,
                     'required_strength': 0, 'required_intelligence': 0, 'required_dexterity': 0,
                     'required_willpower': 0,
                     'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                     'water_penetration': 0.0},
    'rusty_warhmammer': {'name': 'Rusty Warhammer', 'description': 'TODO', 'level': 1, 'weight': 8,
                         '_weapon_type': WeaponType.hammer.value, 'bonus_strength': 2, 'bonus_intelligence': 0,
                         'bonus_dexterity': 0, 'bonus_willpower': 0, 'bonus_health': 0, 'bonus_stamina': 0,
                         'bonus_mana': 0,
                         'bonus_init': 0, 'base_crit_chance': 0.05, 'damages': [[1, 6, Elements.earth.value]],
                         'crit_damage': 0,
                         'required_strength': 0, 'required_intelligence': 0, 'required_dexterity': 0,
                         'required_willpower': 0,
                         'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                         'water_penetration': 0.0},
    'stone_hammer': {'name': 'Stone Hammer', 'description': 'TODO', 'level': 3, 'weight': 5,
                     '_weapon_type': WeaponType.hammer.value, 'bonus_strength': 4, 'bonus_intelligence': 0,
                     'bonus_dexterity': 0, 'bonus_willpower': 0, 'bonus_health': 0, 'bonus_stamina': 0, 'bonus_mana': 0,
                     'bonus_init': 0, 'base_crit_chance': 0.05, 'damages': [[1, 4, Elements.earth.value]],
                     'crit_damage': 0,
                     'required_strength': 4, 'required_intelligence': 0, 'required_dexterity': 0,
                     'required_willpower': 0,
                     'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                     'water_penetration': 0.0},
    'stone_warhmammer': {'name': 'Stone Warhammer', 'description': 'TODO', 'level': 3, 'weight': 10,
                         '_weapon_type': WeaponType.hammer.value, 'bonus_strength': 4, 'bonus_intelligence': 0,
                         'bonus_dexterity': 0, 'bonus_willpower': 0, 'bonus_health': 0, 'bonus_stamina': 0,
                         'bonus_mana': 0,
                         'bonus_init': 0, 'base_crit_chance': 0.05, 'damages': [[1, 6, Elements.earth.value]],
                         'crit_damage': 0,
                         'required_strength': 6, 'required_intelligence': 0, 'required_dexterity': 0,
                         'required_willpower': 0,
                         'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                         'water_penetration': 0.0},
    # Sword/Int
    'rusty_longsword': {'name': 'Rusty Longsword', 'description': 'TODO', 'level': 1, 'weight': 3,
                        '_weapon_type': WeaponType.sword.value, 'bonus_strength': 0, 'bonus_intelligence': 2,
                        'bonus_dexterity': 0, 'bonus_willpower': 0, 'bonus_health': 0, 'bonus_stamina': 0,
                        'bonus_mana': 0,
                        'bonus_init': 0, 'base_crit_chance': 0.05, 'damages': [[1, 4, Elements.earth.value]],
                        'crit_damage': 0,
                        'required_strength': 0, 'required_intelligence': 0, 'required_dexterity': 0,
                        'required_willpower': 0,
                        'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                        'water_penetration': 0.0},
    'rusty_greatsword': {'name': 'Rusty Greatsword', 'description': 'TODO', 'level': 1, 'weight': 8,
                         '_weapon_type': WeaponType.sword.value, 'bonus_strength': 0, 'bonus_intelligence': 4,
                         'bonus_dexterity': 0, 'bonus_willpower': 0, 'bonus_health': 0, 'bonus_stamina': 0,
                         'bonus_mana': 0,
                         'bonus_init': 0, 'base_crit_chance': 0.05, 'damages': [[1, 6, Elements.earth.value]],
                         'crit_damage': 0,
                         'required_strength': 0, 'required_intelligence': 0, 'required_dexterity': 0,
                         'required_willpower': 0,
                         'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                         'water_penetration': 0.0},
    'stone_longsword': {'name': 'Stone Longsword', 'description': 'TODO', 'level': 3, 'weight': 5,
                        '_weapon_type': WeaponType.sword.value, 'bonus_strength': 0, 'bonus_intelligence': 4,
                        'bonus_dexterity': 0, 'bonus_willpower': 0, 'bonus_health': 0, 'bonus_stamina': 0,
                        'bonus_mana': 0,
                        'bonus_init': 0, 'base_crit_chance': 0.05, 'damages': [[1, 4, Elements.earth.value]],
                        'crit_damage': 0,
                        'required_strength': 0, 'required_intelligence': 4, 'required_dexterity': 0,
                        'required_willpower': 0,
                        'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                        'water_penetration': 0.0},
    'stone_greatsword': {'name': 'Stone Greatsword', 'description': 'TODO', 'level': 3, 'weight': 10,
                         '_weapon_type': WeaponType.sword.value, 'bonus_strength': 0, 'bonus_intelligence': 2,
                         'bonus_dexterity': 0, 'bonus_willpower': 0, 'bonus_health': 0, 'bonus_stamina': 0,
                         'bonus_mana': 0,
                         'bonus_init': 0, 'base_crit_chance': 0.05, 'damages': [[1, 6, Elements.earth.value]],
                         'crit_damage': 0,
                         'required_strength': 0, 'required_intelligence': 6, 'required_dexterity': 0,
                         'required_willpower': 0,
                         'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                         'water_penetration': 0.0},
    # Dagger/Dex
    'rusty_shiv': {'name': 'Rusty Shiv', 'description': 'TODO', 'level': 1, 'weight': 1,
                   '_weapon_type': WeaponType.dagger.value, 'bonus_strength': 0, 'bonus_intelligence': 0,
                   'bonus_dexterity': 2, 'bonus_willpower': 0, 'bonus_health': 0, 'bonus_stamina': 0, 'bonus_mana': 0,
                   'bonus_init': 0, 'base_crit_chance': 0.08, 'damages': [[1, 3, Elements.earth.value]],
                   'crit_damage': 0,
                   'required_strength': 0, 'required_intelligence': 0, 'required_dexterity': 0, 'required_willpower': 0,
                   'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                   'water_penetration': 0.0},
    'rusty_dagger': {'name': 'Rusty Dagger', 'description': 'TODO', 'level': 1, 'weight': 2,
                     '_weapon_type': WeaponType.dagger.value, 'bonus_strength': 0, 'bonus_intelligence': 0,
                     'bonus_dexterity': 2, 'bonus_willpower': 0, 'bonus_health': 0, 'bonus_stamina': 0, 'bonus_mana': 0,
                     'bonus_init': 0, 'base_crit_chance': 0.07, 'damages': [[1, 5, Elements.earth.value]],
                     'crit_damage': 0,
                     'required_strength': 0, 'required_intelligence': 0, 'required_dexterity': 0,
                     'required_willpower': 0,
                     'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                     'water_penetration': 0.0},
    'stone_shiv': {'name': 'Stone Shiv', 'description': 'TODO', 'level': 3, 'weight': 3,
                   '_weapon_type': WeaponType.dagger.value, 'bonus_strength': 0, 'bonus_intelligence': 0,
                   'bonus_dexterity': 4, 'bonus_willpower': 0, 'bonus_health': 0, 'bonus_stamina': 0, 'bonus_mana': 0,
                   'bonus_init': 0, 'base_crit_chance': 0.08, 'damages': [[1, 3, Elements.earth.value]],
                   'crit_damage': 0,
                   'required_strength': 0, 'required_intelligence': 0, 'required_dexterity': 4, 'required_willpower': 0,
                   'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                   'water_penetration': 0.0},
    'stone_dagger': {'name': 'Stone Dagger', 'description': 'TODO', 'level': 3, 'weight': 4,
                     '_weapon_type': WeaponType.dagger.value, 'bonus_strength': 0, 'bonus_intelligence': 0,
                     'bonus_dexterity': 4, 'bonus_willpower': 0, 'bonus_health': 0, 'bonus_stamina': 0, 'bonus_mana': 0,
                     'bonus_init': 0, 'base_crit_chance': 0.07, 'damages': [[1, 5, Elements.earth.value]],
                     'crit_damage': 0,
                     'required_strength': 0, 'required_intelligence': 0, 'required_dexterity': 6,
                     'required_willpower': 0,
                     'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                     'water_penetration': 0.0},
    # Staff/Will
    'rusty_scepter': {'name': 'Rusty Scepter', 'description': 'TODO', 'level': 1, 'weight': 2,
                      '_weapon_type': WeaponType.staff.value, 'bonus_strength': 0, 'bonus_intelligence': 0,
                      'bonus_dexterity': 0, 'bonus_willpower': 2, 'bonus_health': 0, 'bonus_stamina': 0,
                      'bonus_mana': 0,
                      'bonus_init': 0, 'base_crit_chance': 0.05, 'damages': [[1, 4, Elements.earth.value]],
                      'crit_damage': 0,
                      'required_strength': 0, 'required_intelligence': 0, 'required_dexterity': 0,
                      'required_willpower': 0,
                      'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                      'water_penetration': 0.0},
    'rough_staff': {'name': 'Rough Staff', 'description': 'TODO', 'level': 1, 'weight': 5,
                    '_weapon_type': WeaponType.staff.value, 'bonus_strength': 0, 'bonus_intelligence': 0,
                    'bonus_dexterity': 0, 'bonus_willpower': 2, 'bonus_health': 0, 'bonus_stamina': 0, 'bonus_mana': 0,
                    'bonus_init': 0, 'base_crit_chance': 0.05, 'damages': [[1, 6, Elements.earth.value]],
                    'crit_damage': 0,
                    'required_strength': 0, 'required_intelligence': 0, 'required_dexterity': 0,
                    'required_willpower': 0,
                    'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                    'water_penetration': 0.0},
    'stone_scepter': {'name': 'Stone Scepter', 'description': 'TODO', 'level': 3, 'weight': 4,
                      '_weapon_type': WeaponType.staff.value, 'bonus_strength': 0, 'bonus_intelligence': 0,
                      'bonus_dexterity': 0, 'bonus_willpower': 4, 'bonus_health': 0, 'bonus_stamina': 0,
                      'bonus_mana': 0,
                      'bonus_init': 0, 'base_crit_chance': 0.05, 'damages': [[1, 4, Elements.earth.value]],
                      'crit_damage': 0,
                      'required_strength': 0, 'required_intelligence': 0, 'required_dexterity': 0,
                      'required_willpower': 4,
                      'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                      'water_penetration': 0.0},
    'driftwood_staff': {'name': 'Driftwood Staff', 'description': 'TODO', 'level': 3, 'weight': 6,
                        '_weapon_type': WeaponType.staff.value, 'bonus_strength': 0, 'bonus_intelligence': 0,
                        'bonus_dexterity': 0, 'bonus_willpower': 4, 'bonus_health': 0, 'bonus_stamina': 0,
                        'bonus_mana': 0,
                        'bonus_init': 0, 'base_crit_chance': 0.05, 'damages': [[1, 6, Elements.earth.value]],
                        'crit_damage': 0,
                        'required_strength': 0, 'required_intelligence': 0, 'required_dexterity': 0,
                        'required_willpower': 6,
                        'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                        'water_penetration': 0.0},
    # Axe/Str+Int
    'rusty_war_axe': {'name': 'Rusty War Axe', 'description': 'TODO', 'level': 1, 'weight': 3,
                      '_weapon_type': WeaponType.axe.value, 'bonus_strength': 1, 'bonus_intelligence': 1,
                      'bonus_dexterity': 0, 'bonus_willpower': 0, 'bonus_health': 0, 'bonus_stamina': 0,
                      'bonus_mana': 0,
                      'bonus_init': 0, 'base_crit_chance': 0.05, 'damages': [[1, 4, Elements.earth.value]],
                      'crit_damage': 0,
                      'required_strength': 0, 'required_intelligence': 0, 'required_dexterity': 0,
                      'required_willpower': 0,
                      'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                      'water_penetration': 0.0},
    'rusty_battle_axe': {'name': 'Rusty Battle Axe', 'description': 'TODO', 'level': 1, 'weight': 8,
                         '_weapon_type': WeaponType.axe.value, 'bonus_strength': 1, 'bonus_intelligence': 1,
                         'bonus_dexterity': 0, 'bonus_willpower': 0, 'bonus_health': 0, 'bonus_stamina': 0,
                         'bonus_mana': 0,
                         'bonus_init': 0, 'base_crit_chance': 0.05, 'damages': [[1, 6, Elements.earth.value]],
                         'crit_damage': 0,
                         'required_strength': 0, 'required_intelligence': 0, 'required_dexterity': 0,
                         'required_willpower': 0,
                         'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                         'water_penetration': 0.0},
    'stone_war_axe': {'name': 'Stone War Axe', 'description': 'TODO', 'level': 3, 'weight': 5,
                      '_weapon_type': WeaponType.axe.value, 'bonus_strength': 2, 'bonus_intelligence': 2,
                      'bonus_dexterity': 0, 'bonus_willpower': 0, 'bonus_health': 0, 'bonus_stamina': 0,
                      'bonus_mana': 0,
                      'bonus_init': 0, 'base_crit_chance': 0.05, 'damages': [[1, 4, Elements.earth.value]],
                      'crit_damage': 0,
                      'required_strength': 2, 'required_intelligence': 2, 'required_dexterity': 0,
                      'required_willpower': 0,
                      'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                      'water_penetration': 0.0},
    'stone_battle_axe': {'name': 'STone Battle Axe', 'description': 'TODO', 'level': 3, 'weight': 10,
                         '_weapon_type': WeaponType.axe.value, 'bonus_strength': 2, 'bonus_intelligence': 2,
                         'bonus_dexterity': 0, 'bonus_willpower': 0, 'bonus_health': 0, 'bonus_stamina': 0,
                         'bonus_mana': 0,
                         'bonus_init': 0, 'base_crit_chance': 0.05, 'damages': [[1, 6, Elements.earth.value]],
                         'crit_damage': 0,
                         'required_strength': 3, 'required_intelligence': 3, 'required_dexterity': 0,
                         'required_willpower': 0,
                         'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                         'water_penetration': 0.0},
    # Spear/Str+Dex
    'rusty_spear': {'name': 'Rusty Spear', 'description': 'TODO', 'level': 1, 'weight': 4,
                    '_weapon_type': WeaponType.spear.value, 'bonus_strength': 1, 'bonus_intelligence': 0,
                    'bonus_dexterity': 1, 'bonus_willpower': 0, 'bonus_health': 0, 'bonus_stamina': 0,
                    'bonus_mana': 0,
                    'bonus_init': 0, 'base_crit_chance': 0.06, 'damages': [[1, 4, Elements.earth.value]],
                    'crit_damage': 0,
                    'required_strength': 0, 'required_intelligence': 0, 'required_dexterity': 0,
                    'required_willpower': 0,
                    'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                    'water_penetration': 0.0},
    'rusty_lance': {'name': 'Rusty Lance', 'description': 'TODO', 'level': 1, 'weight': 8,
                    '_weapon_type': WeaponType.spear.value, 'bonus_strength': 1, 'bonus_intelligence': 0,
                    'bonus_dexterity': 1, 'bonus_willpower': 0, 'bonus_health': 0, 'bonus_stamina': 0,
                    'bonus_mana': 0,
                    'bonus_init': 0, 'base_crit_chance': 0.06, 'damages': [[1, 6, Elements.earth.value]],
                    'crit_damage': 0,
                    'required_strength': 0, 'required_intelligence': 0, 'required_dexterity': 0,
                    'required_willpower': 0,
                    'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                    'water_penetration': 0.0},
    'stone_spear': {'name': 'Stone Spear', 'description': 'TODO', 'level': 3, 'weight': 6,
                    '_weapon_type': WeaponType.spear.value, 'bonus_strength': 2, 'bonus_intelligence': 0,
                    'bonus_dexterity': 2, 'bonus_willpower': 0, 'bonus_health': 0, 'bonus_stamina': 0,
                    'bonus_mana': 0,
                    'bonus_init': 0, 'base_crit_chance': 0.06, 'damages': [[1, 4, Elements.earth.value]],
                    'crit_damage': 0,
                    'required_strength': 2, 'required_intelligence': 0, 'required_dexterity': 2,
                    'required_willpower': 0,
                    'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                    'water_penetration': 0.0},
    'stone_lance': {'name': 'Stone Lance', 'description': 'TODO', 'level': 3, 'weight': 10,
                    '_weapon_type': WeaponType.spear.value, 'bonus_strength': 2, 'bonus_intelligence': 0,
                    'bonus_dexterity': 2, 'bonus_willpower': 0, 'bonus_health': 0, 'bonus_stamina': 0,
                    'bonus_mana': 0,
                    'bonus_init': 0, 'base_crit_chance': 0.06, 'damages': [[1, 6, Elements.earth.value]],
                    'crit_damage': 0,
                    'required_strength': 3, 'required_intelligence': 0, 'required_dexterity': 3,
                    'required_willpower': 0,
                    'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                    'water_penetration': 0.0},
    # Flail/Str+Will
    'rusty_morning_star': {'name': 'Rusty Morning Star', 'description': 'TODO', 'level': 1, 'weight': 4,
                           '_weapon_type': WeaponType.flail.value, 'bonus_strength': 1, 'bonus_intelligence': 0,
                           'bonus_dexterity': 0, 'bonus_willpower': 1, 'bonus_health': 0, 'bonus_stamina': 0,
                           'bonus_mana': 0,
                           'bonus_init': 0, 'base_crit_chance': 0.05, 'damages': [[1, 4, Elements.earth.value]],
                           'crit_damage': 0,
                           'required_strength': 0, 'required_intelligence': 0, 'required_dexterity': 0,
                           'required_willpower': 0,
                           'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                           'water_penetration': 0.0},
    'rusty_flail': {'name': 'Rusty Flail', 'description': 'TODO', 'level': 1, 'weight': 8,
                    '_weapon_type': WeaponType.flail.value, 'bonus_strength': 1, 'bonus_intelligence': 0,
                    'bonus_dexterity': 0, 'bonus_willpower': 1, 'bonus_health': 0, 'bonus_stamina': 0,
                    'bonus_mana': 0,
                    'bonus_init': 0, 'base_crit_chance': 0.05, 'damages': [[1, 6, Elements.earth.value]],
                    'crit_damage': 0,
                    'required_strength': 0, 'required_intelligence': 0, 'required_dexterity': 0,
                    'required_willpower': 0,
                    'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                    'water_penetration': 0.0},
    'stone_morning_star': {'name': 'Stone Morning Star', 'description': 'TODO', 'level': 3, 'weight': 6,
                           '_weapon_type': WeaponType.flail.value, 'bonus_strength': 2, 'bonus_intelligence': 0,
                           'bonus_dexterity': 0, 'bonus_willpower': 2, 'bonus_health': 0, 'bonus_stamina': 0,
                           'bonus_mana': 0,
                           'bonus_init': 0, 'base_crit_chance': 0.05, 'damages': [[1, 4, Elements.earth.value]],
                           'crit_damage': 0,
                           'required_strength': 2, 'required_intelligence': 0, 'required_dexterity': 0,
                           'required_willpower': 2,
                           'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                           'water_penetration': 0.0},
    'stone_flail': {'name': 'Stone Flail', 'description': 'TODO', 'level': 3, 'weight': 10,
                    '_weapon_type': WeaponType.flail.value, 'bonus_strength': 2, 'bonus_intelligence': 1,
                    'bonus_dexterity': 0, 'bonus_willpower': 2, 'bonus_health': 0, 'bonus_stamina': 0,
                    'bonus_mana': 0,
                    'bonus_init': 0, 'base_crit_chance': 0.05, 'damages': [[1, 6, Elements.earth.value]],
                    'crit_damage': 0,
                    'required_strength': 3, 'required_intelligence': 0, 'required_dexterity': 0,
                    'required_willpower': 3,
                    'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                    'water_penetration': 0.0},
    # Fist/Int+Dex
    'rusty_katar': {'name': 'Rusty Katar', 'description': 'TODO', 'level': 1, 'weight': 2,
                    '_weapon_type': WeaponType.fist.value, 'bonus_strength': 0, 'bonus_intelligence': 1,
                    'bonus_dexterity': 1, 'bonus_willpower': 0, 'bonus_health': 0, 'bonus_stamina': 0,
                    'bonus_mana': 0,
                    'bonus_init': 0, 'base_crit_chance': 0.06, 'damages': [[1, 4, Elements.earth.value]],
                    'crit_damage': 0,
                    'required_strength': 0, 'required_intelligence': 0, 'required_dexterity': 0,
                    'required_willpower': 0,
                    'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                    'water_penetration': 0.0},
    'rusty_claw': {'name': 'Rusty Claw', 'description': 'TODO', 'level': 1, 'weight': 3,
                   '_weapon_type': WeaponType.fist.value, 'bonus_strength': 0, 'bonus_intelligence': 1,
                   'bonus_dexterity': 1, 'bonus_willpower': 0, 'bonus_health': 0, 'bonus_stamina': 0,
                   'bonus_mana': 0,
                   'bonus_init': 0, 'base_crit_chance': 0.06, 'damages': [[1, 6, Elements.earth.value]],
                   'crit_damage': 0,
                   'required_strength': 0, 'required_intelligence': 0, 'required_dexterity': 0,
                   'required_willpower': 0,
                   'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                   'water_penetration': 0.0},
    'stone_katar': {'name': 'Stone Katar', 'description': 'TODO', 'level': 3, 'weight': 4,
                    '_weapon_type': WeaponType.fist.value, 'bonus_strength': 0, 'bonus_intelligence': 2,
                    'bonus_dexterity': 2, 'bonus_willpower': 0, 'bonus_health': 0, 'bonus_stamina': 0,
                    'bonus_mana': 0,
                    'bonus_init': 0, 'base_crit_chance': 0.06, 'damages': [[1, 4, Elements.earth.value]],
                    'crit_damage': 0,
                    'required_strength': 0, 'required_intelligence': 2, 'required_dexterity': 2,
                    'required_willpower': 0,
                    'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                    'water_penetration': 0.0},
    'stone_claw': {'name': 'Stone Claw', 'description': 'TODO', 'level': 3, 'weight': 5,
                   '_weapon_type': WeaponType.fist.value, 'bonus_strength': 0, 'bonus_intelligence': 2,
                   'bonus_dexterity': 2, 'bonus_willpower': 0, 'bonus_health': 0, 'bonus_stamina': 0,
                   'bonus_mana': 0,
                   'bonus_init': 0, 'base_crit_chance': 0.06, 'damages': [[1, 6, Elements.earth.value]],
                   'crit_damage': 0,
                   'required_strength': 0, 'required_intelligence': 3, 'required_dexterity': 3,
                   'required_willpower': 0,
                   'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                   'water_penetration': 0.0},
    # Magic/Int+Will
    'rough_wand': {'name': 'Rough Wand', 'description': 'TODO', 'level': 1, 'weight': 2,
                   '_weapon_type': WeaponType.magic.value, 'bonus_strength': 0, 'bonus_intelligence': 1,
                   'bonus_dexterity': 0, 'bonus_willpower': 1, 'bonus_health': 0, 'bonus_stamina': 0,
                   'bonus_mana': 10,
                   'bonus_init': 0, 'base_crit_chance': 0.04, 'damages': [[1, 2, Elements.earth.value]],
                   'crit_damage': 5,
                   'required_strength': 0, 'required_intelligence': 0, 'required_dexterity': 0,
                   'required_willpower': 0,
                   'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                   'water_penetration': 0.0},
    'cracked_orb': {'name': 'Cracked Orb', 'description': 'TODO', 'level': 1, 'weight': 3,
                    '_weapon_type': WeaponType.magic.value, 'bonus_strength': 0, 'bonus_intelligence': 1,
                    'bonus_dexterity': 0, 'bonus_willpower': 1, 'bonus_health': 0, 'bonus_stamina': 0,
                    'bonus_mana': 20,
                    'bonus_init': 0, 'base_crit_chance': 0.01, 'damages': [[1, 1, Elements.earth.value]],
                    'crit_damage': 0,
                    'required_strength': 0, 'required_intelligence': 0, 'required_dexterity': 0,
                    'required_willpower': 0,
                    'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                    'water_penetration': 0.0},
    'driftwood_wand': {'name': 'Driftwood Wand', 'description': 'TODO', 'level': 3, 'weight': 2,
                       '_weapon_type': WeaponType.magic.value, 'bonus_strength': 0, 'bonus_intelligence': 2,
                       'bonus_dexterity': 0, 'bonus_willpower': 2, 'bonus_health': 0, 'bonus_stamina': 0,
                       'bonus_mana': 15,
                       'bonus_init': 0, 'base_crit_chance': 0.04, 'damages': [[1, 2, Elements.earth.value]],
                       'crit_damage': 5,
                       'required_strength': 0, 'required_intelligence': 2, 'required_dexterity': 0,
                       'required_willpower': 2,
                       'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                       'water_penetration': 0.0},
    'dull_orb': {'name': 'Dull Orb', 'description': 'TODO', 'level': 3, 'weight': 3,
                 '_weapon_type': WeaponType.magic.value, 'bonus_strength': 0, 'bonus_intelligence': 2,
                 'bonus_dexterity': 0, 'bonus_willpower': 2, 'bonus_health': 0, 'bonus_stamina': 0,
                 'bonus_mana': 30,
                 'bonus_init': 0, 'base_crit_chance': 0.01, 'damages': [[1, 1, Elements.earth.value]],
                 'crit_damage': 0,
                 'required_strength': 0, 'required_intelligence': 3, 'required_dexterity': 0,
                 'required_willpower': 3,
                 'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                 'water_penetration': 0.0},
    # Thrown/Dex+Will
    'rusty_darts': {'name': 'Rusty Darts', 'description': 'TODO', 'level': 1, 'weight': 1,
                    '_weapon_type': WeaponType.thrown.value, 'bonus_strength': 0, 'bonus_intelligence': 0,
                    'bonus_dexterity': 1, 'bonus_willpower': 1, 'bonus_health': 0, 'bonus_stamina': 0,
                    'bonus_mana': 0,
                    'bonus_init': 0, 'base_crit_chance': 0.06, 'damages': [[1, 3, Elements.earth.value]],
                    'crit_damage': 3,
                    'required_strength': 0, 'required_intelligence': 0, 'required_dexterity': 0,
                    'required_willpower': 0,
                    'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                    'water_penetration': 0.0},
    'rusty_chakram': {'name': 'Rusty Chakram', 'description': 'TODO', 'level': 1, 'weight': 3,
                      '_weapon_type': WeaponType.thrown.value, 'bonus_strength': 0, 'bonus_intelligence': 0,
                      'bonus_dexterity': 1, 'bonus_willpower': 1, 'bonus_health': 0, 'bonus_stamina': 0,
                      'bonus_mana': 0,
                      'bonus_init': 0, 'base_crit_chance': 0.06, 'damages': [[1, 5, Elements.earth.value]],
                      'crit_damage': 3,
                      'required_strength': 0, 'required_intelligence': 0, 'required_dexterity': 0,
                      'required_willpower': 0,
                      'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                      'water_penetration': 0.0},
    'stone_darts': {'name': 'Stone Darts', 'description': 'TODO', 'level': 3, 'weight': 3,
                    '_weapon_type': WeaponType.thrown.value, 'bonus_strength': 0, 'bonus_intelligence': 0,
                    'bonus_dexterity': 2, 'bonus_willpower': 2, 'bonus_health': 0, 'bonus_stamina': 0,
                    'bonus_mana': 0,
                    'bonus_init': 0, 'base_crit_chance': 0.06, 'damages': [[1, 3, Elements.earth.value]],
                    'crit_damage': 3,
                    'required_strength': 0, 'required_intelligence': 0, 'required_dexterity': 2,
                    'required_willpower': 2,
                    'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                    'water_penetration': 0.0},
    'stone_chakram': {'name': 'Stone Chakram', 'description': 'TODO', 'level': 3, 'weight': 5,
                      '_weapon_type': WeaponType.thrown.value, 'bonus_strength': 0, 'bonus_intelligence': 0,
                      'bonus_dexterity': 2, 'bonus_willpower': 2, 'bonus_health': 0, 'bonus_stamina': 0,
                      'bonus_mana': 0,
                      'bonus_init': 0, 'base_crit_chance': 0.06, 'damages': [[1, 5, Elements.earth.value]],
                      'crit_damage': 3,
                      'required_strength': 0, 'required_intelligence': 0, 'required_dexterity': 3,
                      'required_willpower': 3,
                      'earth_penetration': 0.0, 'fire_penetration': 0.0, 'electricity_penetration': 0.0,
                      'water_penetration': 0.0},
}
