gemstones = {
    'tourmaline': {'name': 'Tourmaline',
                   'description': 'A hexagonal piece of translucent green boron silicate.',
                   'effect': 'bonus_strength',
                   'tiers': [
                       {'name': 'Mote', 'amount': 1},
                       {'name': 'Speck', 'amount': 2},
                       {'name': 'Sliver', 'amount': 3},
                       {'name': 'Shard', 'amount': 5},
                       {'name': 'Fragment', 'amount': 8},
                       {'name': 'Round', 'amount': 13},
                       {'name': 'Square', 'amount': 21},
                       {'name': 'Oval', 'amount': 34},
                       {'name': 'Marquise', 'amount': 55},
                   ]},
    'garnet': {'name': 'Garnet',
               'description': 'A cubic piece of translucent dark red almandine.',
               'effect': 'bonus_intelligence',
               'tiers': [
                   {'name': 'Mote', 'amount': 1},
                   {'name': 'Speck', 'amount': 2},
                   {'name': 'Sliver', 'amount': 3},
                   {'name': 'Shard', 'amount': 5},
                   {'name': 'Fragment', 'amount': 8},
                   {'name': 'Round', 'amount': 13},
                   {'name': 'Square', 'amount': 21},
                   {'name': 'Oval', 'amount': 34},
                   {'name': 'Marquise', 'amount': 55},
               ]},
    'citrine': {'name': 'Citrine',
                'description': 'A faceted piece of transparent yellow-orange quartz.',
                'effect': 'bonus_dexterity',
                'tiers': [
                    {'name': 'Mote', 'amount': 1},
                    {'name': 'Speck', 'amount': 2},
                    {'name': 'Sliver', 'amount': 3},
                    {'name': 'Shard', 'amount': 5},
                    {'name': 'Fragment', 'amount': 8},
                    {'name': 'Round', 'amount': 13},
                    {'name': 'Square', 'amount': 21},
                    {'name': 'Oval', 'amount': 34},
                    {'name': 'Marquise', 'amount': 55},
                ]},
    'lapis': {'name': 'Lapis',
              'description': 'A smooth piece of ultramarine blue metamorphic stone.',
              'effect': 'bonus_willpower',
              'tiers': [
                  {'name': 'Mote', 'amount': 1},
                  {'name': 'Speck', 'amount': 2},
                  {'name': 'Sliver', 'amount': 3},
                  {'name': 'Shard', 'amount': 5},
                  {'name': 'Fragment', 'amount': 8},
                  {'name': 'Round', 'amount': 13},
                  {'name': 'Square', 'amount': 21},
                  {'name': 'Oval', 'amount': 34},
                  {'name': 'Marquise', 'amount': 55},
              ]},
    'marble': {'name': 'Marble',
               'description': 'A smooth piece of faceted milky white metamorphic rock.',
               'effect': 'bonus_health',
               'tiers': [
                   {'name': 'Mote', 'amount': 1},
                   {'name': 'Speck', 'amount': 2},
                   {'name': 'Sliver', 'amount': 3},
                   {'name': 'Shard', 'amount': 5},
                   {'name': 'Fragment', 'amount': 8},
                   {'name': 'Round', 'amount': 13},
                   {'name': 'Square', 'amount': 21},
                   {'name': 'Oval', 'amount': 34},
                   {'name': 'Marquise', 'amount': 55},
               ]},
    'obsidian': {'name': 'Obsidian',
                 'description': 'A sharp-edged piece of black volcanic glass with conchoidal fractures.',
                 'effect': 'bonus_stamina',
                 'tiers': [
                     {'name': 'Mote', 'amount': 1},
                     {'name': 'Speck', 'amount': 2},
                     {'name': 'Sliver', 'amount': 3},
                     {'name': 'Shard', 'amount': 5},
                     {'name': 'Fragment', 'amount': 8},
                     {'name': 'Round', 'amount': 13},
                     {'name': 'Square', 'amount': 21},
                     {'name': 'Oval', 'amount': 34},
                     {'name': 'Marquise', 'amount': 55},
                 ]},
    'amethyst': {'name': 'Amethyst',
                 'description': 'A hexagonal piece of translucent deep purple quartz.',
                 'effect': 'bonus_mana',
                 'tiers': [
                     {'name': 'Mote', 'amount': 1},
                     {'name': 'Speck', 'amount': 2},
                     {'name': 'Sliver', 'amount': 3},
                     {'name': 'Shard', 'amount': 5},
                     {'name': 'Fragment', 'amount': 8},
                     {'name': 'Round', 'amount': 13},
                     {'name': 'Square', 'amount': 21},
                     {'name': 'Oval', 'amount': 34},
                     {'name': 'Marquise', 'amount': 55},
                 ]},
    'quartz': {'name': 'Quartz',
               'description': 'A hexagonal piece of translucent white quartz.',
               'effect': 'bonus_health_regen',
               'tiers': [
                   {'name': 'Mote', 'amount': 1},
                   {'name': 'Speck', 'amount': 2},
                   {'name': 'Sliver', 'amount': 3},
                   {'name': 'Shard', 'amount': 4},
                   {'name': 'Fragment', 'amount': 5},
                   {'name': 'Round', 'amount': 6},
                   {'name': 'Square', 'amount': 7},
                   {'name': 'Oval', 'amount': 8},
                   {'name': 'Marquise', 'amount': 9},
               ]},
    'beryl': {'name': 'Beryl',
              'description': 'A hexagonal piece of transparent greenish yellow silicate mineral.',
              'effect': 'bonus_stamina_regen',
              'tiers': [
                  {'name': 'Mote', 'amount': 1},
                  {'name': 'Speck', 'amount': 2},
                  {'name': 'Sliver', 'amount': 3},
                  {'name': 'Shard', 'amount': 4},
                  {'name': 'Fragment', 'amount': 5},
                  {'name': 'Round', 'amount': 6},
                  {'name': 'Square', 'amount': 7},
                  {'name': 'Oval', 'amount': 8},
                  {'name': 'Marquise', 'amount': 9},
              ]},
    'opal': {'name': 'Opal',
             'description': 'A delicate piece of blue and violet crystal mineraloid that plays with the light.',
             'effect': 'bonus_mana_regen',
             'tiers': [
                 {'name': 'Mote', 'amount': 1},
                 {'name': 'Speck', 'amount': 2},
                 {'name': 'Sliver', 'amount': 3},
                 {'name': 'Shard', 'amount': 4},
                 {'name': 'Fragment', 'amount': 5},
                 {'name': 'Round', 'amount': 6},
                 {'name': 'Square', 'amount': 7},
                 {'name': 'Oval', 'amount': 8},
                 {'name': 'Marquise', 'amount': 9},
             ]},
    'hematite': {'name': 'Hematite',
                 'description': 'A metallic piece of opaque black and steel-gray mineral.',
                 'effect': 'bonus_carry',
                 'tiers': [
                     {'name': 'Mote', 'amount': 2},
                     {'name': 'Speck', 'amount': 4},
                     {'name': 'Sliver', 'amount': 8},
                     {'name': 'Shard', 'amount': 16},
                     {'name': 'Fragment', 'amount': 32},
                     {'name': 'Round', 'amount': 64},
                     {'name': 'Square', 'amount': 128},
                     {'name': 'Oval', 'amount': 256},
                     {'name': 'Marquise', 'amount': 512},
                 ]},
    'moonstone': {'name': 'Moonstone',
                  'description': 'A smooth piece of adularescent white feldspar.',
                  'effect': 'bonus_init',
                  'tiers': [
                      {'name': 'Mote', 'amount': 1},
                      {'name': 'Speck', 'amount': 2},
                      {'name': 'Sliver', 'amount': 3},
                      {'name': 'Shard', 'amount': 5},
                      {'name': 'Fragment', 'amount': 8},
                      {'name': 'Round', 'amount': 13},
                      {'name': 'Square', 'amount': 21},
                      {'name': 'Oval', 'amount': 34},
                      {'name': 'Marquise', 'amount': 55},
                  ]},
    'emerald': {'name': 'Emerald',
                'description': 'A hexagonal piece of transparent green precious beryl.',
                'effect': 'bonus_earth_res',
                'tiers': [
                    {'name': 'Mote', 'amount': 0.01},
                    {'name': 'Speck', 'amount': 0.02},
                    {'name': 'Sliver', 'amount': 0.03},
                    {'name': 'Shard', 'amount': 0.04},
                    {'name': 'Fragment', 'amount': 0.05},
                    {'name': 'Round', 'amount': 0.06},
                    {'name': 'Square', 'amount': 0.07},
                    {'name': 'Oval', 'amount': 0.08},
                    {'name': 'Marquise', 'amount': 0.09},
                ]},
    'ruby': {'name': 'Ruby',
             'description': 'A hexagonal piece of striking red corundum.',
             'effect': 'bonus_fire_res',
             'tiers': [
                 {'name': 'Mote', 'amount': 0.01},
                 {'name': 'Speck', 'amount': 0.02},
                 {'name': 'Sliver', 'amount': 0.03},
                 {'name': 'Shard', 'amount': 0.04},
                 {'name': 'Fragment', 'amount': 0.05},
                 {'name': 'Round', 'amount': 0.06},
                 {'name': 'Square', 'amount': 0.07},
                 {'name': 'Oval', 'amount': 0.08},
                 {'name': 'Marquise', 'amount': 0.09},
             ]},
    'topaz': {'name': 'Topaz',
              'description': 'An orthorhombic piece of transparent yellow-orange silicate.',
              'effect': 'bonus_electricity_res',
              'tiers': [
                  {'name': 'Mote', 'amount': 0.01},
                  {'name': 'Speck', 'amount': 0.02},
                  {'name': 'Sliver', 'amount': 0.03},
                  {'name': 'Shard', 'amount': 0.04},
                  {'name': 'Fragment', 'amount': 0.05},
                  {'name': 'Round', 'amount': 0.06},
                  {'name': 'Square', 'amount': 0.07},
                  {'name': 'Oval', 'amount': 0.08},
                  {'name': 'Marquise', 'amount': 0.09},
              ]},
    'sapphire': {'name': 'Sapphire',
                 'description': 'A hexagonal piece of striking blue corundum.',
                 'effect': 'bonus_water_res',
                 'tiers': [
                     {'name': 'Mote', 'amount': 0.01},
                     {'name': 'Speck', 'amount': 0.02},
                     {'name': 'Sliver', 'amount': 0.03},
                     {'name': 'Shard', 'amount': 0.04},
                     {'name': 'Fragment', 'amount': 0.05},
                     {'name': 'Round', 'amount': 0.06},
                     {'name': 'Square', 'amount': 0.07},
                     {'name': 'Oval', 'amount': 0.08},
                     {'name': 'Marquise', 'amount': 0.09},
                 ]},
    'diamond': {'name': 'Diamond',
                'description': 'A crystal of clear, lustrous, transparent carbon.',
                'effect': 'base_crit_chance',
                'tiers': [
                    {'name': 'Mote', 'amount': 0.01},
                    {'name': 'Speck', 'amount': 0.01},
                    {'name': 'Sliver', 'amount': 0.01},
                    {'name': 'Shard', 'amount': 0.02},
                    {'name': 'Fragment', 'amount': 0.02},
                    {'name': 'Round', 'amount': 0.02},
                    {'name': 'Square', 'amount': 0.03},
                    {'name': 'Oval', 'amount': 0.03},
                    {'name': 'Marquise', 'amount': 0.03},
                ]},
    'sunstone': {'name': 'Sunstone',
                 'description': 'A piece of translucent, creamy pink, aventurescent feldspar.',
                 'effect': 'crit_damage',
                 'tiers': [
                     {'name': 'Mote', 'amount': 1},
                     {'name': 'Speck', 'amount': 2},
                     {'name': 'Sliver', 'amount': 3},
                     {'name': 'Shard', 'amount': 5},
                     {'name': 'Fragment', 'amount': 8},
                     {'name': 'Round', 'amount': 13},
                     {'name': 'Square', 'amount': 21},
                     {'name': 'Oval', 'amount': 34},
                     {'name': 'Marquise', 'amount': 55},
                 ]},
    'serpentine': {'name': 'Serpentine',
                   'description': 'A piece of waxy, opaque green silicate.',
                   'effect': 'earth_penetration',
                   'tiers': [
                       {'name': 'Mote', 'amount': 0.01},
                       {'name': 'Speck', 'amount': 0.02},
                       {'name': 'Sliver', 'amount': 0.03},
                       {'name': 'Shard', 'amount': 0.04},
                       {'name': 'Fragment', 'amount': 0.05},
                       {'name': 'Round', 'amount': 0.06},
                       {'name': 'Square', 'amount': 0.07},
                       {'name': 'Oval', 'amount': 0.08},
                       {'name': 'Marquise', 'amount': 0.09},
                   ]},
    'fire_agate': {'name': 'Fire Agate',
                   'description': 'A piece of brown agate containing hemispheres of red, orange, and yellow flash.',
                   'effect': 'fire_penetration',
                   'tiers': [
                       {'name': 'Mote', 'amount': 0.01},
                       {'name': 'Speck', 'amount': 0.02},
                       {'name': 'Sliver', 'amount': 0.03},
                       {'name': 'Shard', 'amount': 0.04},
                       {'name': 'Fragment', 'amount': 0.05},
                       {'name': 'Round', 'amount': 0.06},
                       {'name': 'Square', 'amount': 0.07},
                       {'name': 'Oval', 'amount': 0.08},
                       {'name': 'Marquise', 'amount': 0.09},
                   ]},
    'zircon': {'name': 'Zircon',
               'description': 'A tetragonal piece of golden yellow, translucent silicate.',
               'effect': 'electricity_penetration',
               'tiers': [
                   {'name': 'Mote', 'amount': 0.01},
                   {'name': 'Speck', 'amount': 0.02},
                   {'name': 'Sliver', 'amount': 0.03},
                   {'name': 'Shard', 'amount': 0.04},
                   {'name': 'Fragment', 'amount': 0.05},
                   {'name': 'Round', 'amount': 0.06},
                   {'name': 'Square', 'amount': 0.07},
                   {'name': 'Oval', 'amount': 0.08},
                   {'name': 'Marquise', 'amount': 0.09},
               ]},
    'fluorite': {'name': 'Fluorite',
                 'description': 'A perfectly octohedronal piece of translucent, sky blue halide.',
                 'effect': 'water_penetration',
                 'tiers': [
                     {'name': 'Mote', 'amount': 0.01},
                     {'name': 'Speck', 'amount': 0.02},
                     {'name': 'Sliver', 'amount': 0.03},
                     {'name': 'Shard', 'amount': 0.04},
                     {'name': 'Fragment', 'amount': 0.05},
                     {'name': 'Round', 'amount': 0.06},
                     {'name': 'Square', 'amount': 0.07},
                     {'name': 'Oval', 'amount': 0.08},
                     {'name': 'Marquise', 'amount': 0.09},
                 ]},
}